language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

php:
  - 5.6
  - 7.3
  - 7.4

env:
    global:
        - TEST_COMMAND="vendor/bin/phpunit"
    matrix:
        - SYMFONY_VERSION=^2.7

matrix:
    fast_finish: true

    include:
        - php: 5.6
          env: SYMFONY_VERSION=^3.2 COMPOSER_MEMORY_LIMIT=-1
        - php: 7.3
          env: SYMFONY_VERSION=^3.2 COMPOSER_MEMORY_LIMIT=-1
        - php: 7.3
          env: SYMFONY_VERSION=^4.0 COMPOSER_MEMORY_LIMIT=-1
        - php: 7.4
          env: SYMFONY_VERSION=^4.0 COMPOSER_MEMORY_LIMIT=-1
        - php: 7.3
          env: SYMFONY_VERSION=^5.0 COMPOSER_MEMORY_LIMIT=-1
        - php: 7.4
          env: SYMFONY_VERSION=^5.0 COMPOSER_MEMORY_LIMIT=-1

before_install:
    - travis_retry composer self-update

install:
    - composer require symfony/symfony:${SYMFONY_VERSION} --no-update
    - composer update ${COMPOSER_FLAGS} --prefer-source --no-interaction

script:
    - $TEST_COMMAND

